cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='summary'),
    path('add/', views.cart_add, name='add'),
    path('delete/', views.cart_delete, name='delete'),

]

chat/urls.py
from django.urls import path
from .views import *

app_name = 'chat'

urlpatterns = [
    path('<int:chat_id>/<int:course_id>', chat_room, name='chat_room'),
    path('create_chat_room/<int:course_id>', create_chat_room, name='create_chat_room'),
    path('contact_options/<int:course_id>', contact_options, name='contact_options'),
    path('contact_options/<int:course_id>/<int:student_id>', contact_options, name='contact_options_for_student'),
    path('contact_email/<int:course_id>', contact_email, name='contact_email'),
    path('contact_email/<int:course_id>/<int:student_id>', contact_email, name='contact_email_for_instructor'),
    path('block/<int:course_id>/<int:student_id>', block_student, name='block_student'),
    path('unblock/<int:course_id>/<int:student_id>', unblock_student, name='unblock_student')
]

scholarstream/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('course.urls', 'course'), namespace='course')),
    path('user/', include('user.urls')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('feedback/', include('feedback.urls')),
    path('chat/', include('chat.urls')),
    path('notifications/', include('notifications.urls')),
]

chat/models.py
from django.db import models
from django.conf import settings

class Chat(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='student_chats', on_delete=models.CASCADE)
    instructor = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='instructor_chats', on_delete=models.CASCADE)
    student_online = models.BooleanField(default=False)
    instructor_online = models.BooleanField(default=False)

class Message(models.Model):
    chat = models.ForeignKey(Chat, related_name='messages', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.author.username}: {self.content[:50]}..."

class Email(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_emails', on_delete=models.CASCADE)
    recipient = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_emails', on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.sender.username} to {self.recipient.username}: {self.content[:50]}..."

chat/forms.py
from django import forms
from tinymce.widgets import TinyMCE

from .models import Email

class EmailForm(forms.ModelForm):
    content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
    class Meta:
        model = Email
        fields = ['subject', 'content',]
    

chat/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.template.loader import render_to_string

import html

from .models import Chat, Message
from course.models import Course
from .forms import EmailForm
from notifications.utils import create_notification
from user.models import BlockedUsers

@login_required
def chat_room(request, chat_id, course_id):
    course = get_object_or_404(Course, pk=course_id)
    messages = Message.objects.filter(chat_id=chat_id).order_by('timestamp')
    chat = Chat.objects.get(pk=chat_id)
    return render(request, 'chat/chat.html', {'chat_id': chat_id, 'course': course, 'messages': messages, 'chat': chat})


@login_required
def create_chat_room(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    instructor = get_user_model().objects.filter(courses = course, user_type='I').first()
    Chat.objects.create(student=request.user, instructor=instructor)
    chat_room = Chat.objects.filter(student=request.user, instructor=instructor).first()
    create_notification(instructor, 'chat', f'You have received a new chat request from {request.user.first_name}.', reverse('chat:chat_room', args=[chat_room.id, course.id]))
    return redirect('chat:chat_room', chat_room.id, course.id)


@login_required
def contact_options(request, course_id, student_id=None):
    course = get_object_or_404(Course, pk=course_id)
    if student_id:
        student = get_user_model().objects.get(pk=student_id)
        last_chat = Chat.objects.filter(student_id=student, instructor=request.user).last()
        return render(request, 'chat/contact_options.html', {'course': course, 'last_chat': last_chat, 'is_instructor': True, 'student_id': student_id})
    else:
        last_chat = Chat.objects.filter(student=request.user, instructor__courses=course).last()
        return render(request, 'chat/contact_options.html', {'course': course, 'last_chat': last_chat, 'is_instructor': False})


@login_required
def contact_email(request, course_id, student_id=None):
    course = get_object_or_404(Course, pk=course_id)
    instructor = get_user_model().objects.filter(courses = course, user_type='I').first()
    is_blocked = BlockedUsers.objects.filter(student=request.user, instructor=instructor, course=course).exists()

    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            email = form.save(commit=False)
            email.sender = request.user
            if student_id:
                email.recipient = get_user_model().objects.get(pk=student_id)
            else:
                email.recipient = get_user_model().objects.filter(courses = course, user_type='I').first()
            email.save()
            email.content = html.unescape(email.content)
            email.content = f"<p><strong>Email sent from {email.sender.first_name}</strong></p><hr><br><br><p>{email.content}</p>"
            email.recipient.email_user(email.subject, email.content, html_message=email.content)
            create_notification(email.recipient, 'email', f'You have received an email from {email.sender.first_name}.')
            if student_id:
                return redirect('chat:contact_options_for_student', course_id, student_id)
            return redirect('chat:contact_options', course_id)
    emailForm = EmailForm()
    return render(request, 'chat/contact_email.html', {'form': emailForm, 'course': course, 'is_blocked': is_blocked})


@login_required
def block_student(request, course_id, student_id):
    if request.user.user_type == 'S':
        return redirect('forbidden')
    student = get_object_or_404(get_user_model(), pk=student_id)
    course = get_object_or_404(Course, pk=course_id)
    BlockedUsers.objects.get_or_create(student=student, course=course, instructor=request.user)
    return redirect('course:list_students', course_id)
    
@login_required
def unblock_student(request, course_id, student_id):
    if request.user.user_type == 'S':
        return redirect('forbidden')
    student = get_object_or_404(get_user_model(), pk=student_id)
    course = get_object_or_404(Course, pk=course_id)
    get_object_or_404(BlockedUsers, student=student, course=course, instructor=request.user).delete()
    return redirect('course:list_students', course_id)
 

chat/templates/chat/chat.html
{% extends 'course/dashboard/base_dashboard.html' %}

{% block content %}
<style>
    #chat-box {
        width: 400px;
        height: 500px;
        border: 1px solid #ccc;
        margin: 20px auto;
        padding: 20px;
    }

    #messages {
        height: 400px;
        overflow-y: scroll;
        border: 1px solid #ddd;
        padding: 10px;
    }

    #student-typing-indicator, #instructor-typing-indicator {
        display: none;
        font-weight: bold;
    }
</style>

<div id="chat-box">
    <div id="messages">
        {% for message in messages %}
            <p>{{ message.author.user_type }}: {{ message.content }}</p>
        {% endfor %}
    </div>
    <br>
    {% if user.user_type == 'I' %}
        <span id="student-typing-indicator">Student is typing...</span>
        <br>
        <span id="student-online-indicator" 
        {% if chat.student_online %}
            style="color:green;display:block;"  
        {% else %} 
            style="color:green;display:none;"  
        {% endif %}
        >Student is online</span>
        <span id="student-offline-indicator" 
        {% if not chat.student_online %}
            style="color:red;display:block;"
        {% else %}
            style="color:red;display:none;"
        {% endif %}
        >Student is offline</span>
    {% else %}
        <span id="instructor-typing-indicator">Instructor is typing...</span>
        <br>
        <span id="instructor-online-indicator" 
        {% if chat.instructor_online %}
            style="color:green;display:block;"
        {% else %}
            style="color:green;display:none;"
        {% endif %}
        >Instructor is online</span>
        <span id="instructor-offline-indicator" 
        {% if not chat.instructor_online %}
            style="color:red;display:block;"
        {% else %}
            style="color:red;display:none;"
        {% endif %}
        >Instructor is offline</span>
    {% endif %}

    <input type="text" id="message-input">
    <button onclick="sendMessage()">Send</button>
</div>

<script>
    window.addEventListener("load", (event) => {
        scrollToBottom();
    });

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/chat/'
        + {{ chat_id }}
        + '/'
    );

    function scrollToBottom() {
        const messages = document.querySelector('#messages');
        messages.scrollTop = messages.scrollHeight;
    }

    chatSocket.onmessage = function(e) {
        const data = JSON.parse(e.data);
        console.log(data)
        const message = data['message'];
        const typing = data['typing'];
        const role = data['role'];

        if (message) {
            document.querySelector("#messages").innerHTML += `<p>${role}: ${message}</p>`;
        }

        const studentTypingIndicator = document.querySelector("#student-typing-indicator");
        const instructorTypingIndicator = document.querySelector("#instructor-typing-indicator");

        if (typing !== undefined) {
            if (role === 'S') {
                if (typing) {
                    studentTypingIndicator.style.display = "block";
                } else {
                    studentTypingIndicator.style.display = "none";
                }
            } else if (role === 'I') {
                if (typing) {
                    instructorTypingIndicator.style.display = "block";
                } else {
                    instructorTypingIndicator.style.display = "none";
                }
            }
        }

        const online = data['online'];
        const studentOnlineIndicator = document.querySelector("#student-online-indicator");
        const studentOfflineIndicator = document.querySelector("#student-offline-indicator");
        const instructorOnlineIndicator = document.querySelector("#instructor-online-indicator");
        const instructorOfflineIndicator = document.querySelector("#instructor-offline-indicator");

        if (online !== undefined) {
            {% if user.user_type == 'I' %}
                if (role === 'S') {
                    if (online) {
                        studentOnlineIndicator.style.display = "block";
                        studentOfflineIndicator.style.display = "none";
                    } else {
                        studentOnlineIndicator.style.display = "none";
                        studentOfflineIndicator.style.display = "block";
                    }
                }
            {% else %}
                if (role === 'I') {
                    if (online) {
                        instructorOnlineIndicator.style.display = "block";
                        instructorOfflineIndicator.style.display = "none";
                    } else {
                        instructorOnlineIndicator.style.display = "none";
                        instructorOfflineIndicator.style.display = "block";
                    }
                }
            {% endif %}
        }

        scrollToBottom();
    };

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    function sendMessage() {
        const messageInput = document.querySelector("#message-input");
        chatSocket.send(JSON.stringify({
            'message': messageInput.value
        }));
        messageInput.value = '';
    }

    let typingTimeout;
    document.querySelector("#message-input").addEventListener("keyup", function() {
        clearTimeout(typingTimeout);
        chatSocket.send(JSON.stringify({'typing': true}));
        typingTimeout = setTimeout(stopTyping, 2000);
    });

    function stopTyping() {
        chatSocket.send(JSON.stringify({'typing': false}));
    }
</script>

{% endblock %}

chat/templates/chat/contact_email.html
{% extends 'course/dashboard/base_dashboard.html' %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<style>

    body {
        background-color: gray;
    }

</style>

<script src="https://cdn.tiny.cloud/1/zpbcq0miun2mhh0iwfiwwh9th7ecy516wt38u17bvmtntwmr/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

<body>

    <br>
    <div class="container col-7 bg-white shadow-md p-5 form-layout">

        {% if user.user_type == 'I' %}
            <h3 class="text-center"> Contact Student by Email </h3>
        {% else %}
            <h3 class="text-center"> Contact Instructor by Email </h3>
        {% endif %}
        <hr><br>

        {% if is_blocked %}
            <h4 class="bg-danger text-center p-3">!! You are blocked from sending emails.</h4>
        {% else %}
            <form method='POST'>

                {% csrf_token %}
                {{ form|crispy }}

                <br><br>
                <button type="submit" class="btn btn-primary btn-lg w-100 btn-block p-2">Send Email</button>
                <br>
            </form>
        {% endif %}

    </div>
    <script>
        tinymce.init({
            selector: 'textarea'
        });
    </script>
</body>

{% endblock content %}

chat/templates/chat/contact_email_template.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 20px;
            max-width: 600px;
            margin: auto;
        }
    </style>
</head>
<body>

<p><strong>Email sent from {{ sender.first_name }}</strong></p>

{{ content }}

</body>
</html>

chat/templates/chat/contact_options.html
{% extends 'course/dashboard/base_dashboard.html' %}

{% block content %}

<div class="container">
    
    <div class="row">
        <div class="col-md-6">
            <div class="card m-5">
                <div class="card-body">
                    {% if is_instructor %}
                        <h5 class="card-title">Contact Student by Email</h5>
                        <p class="card-text">You can just directly email the student with your queries.</p>
                        <a href="{% url 'chat:contact_email_for_instructor' course.id student_id %}" class="btn btn-primary mt-2 w-100">Email Student</a>
                    {% else %}
                        <h5 class="card-title">Contact Instructor by Email</h5>
                        <p class="card-text">You can just directly email the instructor with your queries.</p>
                        <a href="{% url 'chat:contact_email' course.id %}" class="btn btn-primary mt-2 w-100">Email Instructor</a>                    
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card m-5">
                <div class="card-body">
                    {% if is_instructor %}
                        <h5 class="card-title">Contact with Student by Chat</h5>
                        <p class="card-text">You can just directly chat with student.</p>
                        <div class="row">
                            {% if last_chat %}
                                <div class="col-md-5">
                                    <a href="{% url 'chat:chat_room' last_chat.id course.id %}" class="btn btn-primary mt-2">Continue with an existing chat</a>
                                </div>
                            {% else %}
                                <p class="bg-warning">There are no existing chats with the student.</p>
                            {% endif %}
                        </div>
                    {% else %}
                        <h5 class="card-title">Contact with Instructor by Chat</h5>
                        <p class="card-text">You can just directly chat with instructor with your queries.</p>
                        <div class="row">
                            {% if last_chat %}
                                <div class="col-md-5">
                                    <a href="{% url 'chat:create_chat_room' course.id %}" class="btn btn-primary mt-2">Chat with Instructor</a>
                                </div>
                                <span class="col-md-2 mt-4">OR</span>
                                <div class="col-md-5">
                                    <a href="{% url 'chat:chat_room' last_chat.id course.id %}" class="btn btn-primary mt-2">Continue with an existing chat</a>
                                </div>
                            {% else %}
                                <a href="{% url 'chat:create_chat_room' course.id %}" class="btn btn-primary mt-2">Chat with Instructor</a>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

chat/templates/chat/create_chat_room.html
<!-- create_room.html -->

<form method="post" action="{% url 'chat:create_chat_room' %}">
    {% csrf_token %}
    <label for="room_name">Room Name:</label>
    <input type="text" name="room_name" required>
    
    <label for="instructor_id">Select Instructor:</label>
    <select name="instructor_id">
        {% for instructor in instructors %}  <!-- You will need to pass 'instructors' context to the template -->
        <option value="{{ instructor.id }}">{{ instructor.username }}</option>
        {% endfor %}
    </select>
    
    <button type="submit">Create Room</button>
</form>