cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='summary'),
    path('add/', views.cart_add, name='add'),
    path('delete/', views.cart_delete, name='delete'),

]

course/urls.py
from django.urls import path
from . import views
from .views import AddContent

appname = 'course'

urlpatterns = [
    path('add', views.add_course, name='add'),
    path('', views.list_course, name='list'),
    path('<int:pk>/', views.course_dashboard, name='detail'),
    path('<int:pk>/enroll', views.enroll_course, name='enroll'),
    path('<int:pk>/dropout', views.dropout, name='dropout'),
    path('<int:pk>/delete', views.delete_course, name='delete'),
    
    path('<int:course_id>/add_lesson/', views.AddLesson.as_view(), name='add_lesson'),
    path('<int:course_id>/lessons/', views.list_lessons, name='list_lessons'),
    path('<int:course_id>/lesson/<int:lesson_id>/', views.view_lesson, name='view_lesson'),
    path('<int:course_id>/lesson/<int:lesson_id>/add_content/', AddContent.as_view(), name='add_content'),
    path('content/<int:content_id>/', views.view_content, name='view_content'),
    path('<int:course_id>/download_content', views.download_course_content, name='download_course_content'),
    path('<int:course_id>/<int:lesson_id>/download_content', views.download_course_content,
         name='download_lesson_content'),
    path('<int:course_id>/lesson/<int:lesson_id>/delete/', views.delete_lesson, name='delete_lesson'),
    path('<int:course_id>/content/<int:content_id>/delete/', views.delete_content, name='delete_content'),
    path('<int:course_id>/content/<int:content_id>/publish/', views.publish_content, name='publish_content'),
    path('<int:course_id>/content/<int:content_id>/hide/', views.hide_content, name='hide_content'),

    path('<int:course_id>/create_assignment/', views.create_assignment, name='create_assignment'),
    path('<int:course_id>/assignments/', views.list_assignments, name='list_assignments'),
    path('<int:course_id>/assignment/<int:assignment_id>/', views.view_assignment, name='view_assignment'),
    path('<int:course_id>/assignment/<int:assignment_id>/delete/', views.delete_assignment, name='delete_assignment'),
    path('<int:course_id>/assignment/submission/<int:submission_id>/', views.view_assignment_submission,
         name='view_submission'),
    path('<int:course_id>/assignment/<int:assignment_id>/publish/', views.publish_assignment,
         name='publish_assignment'),
    path('<int:course_id>/assignment/<int:assignment_id>/unpublish/', views.hide_assignment, name='hide_assignment'),
    path('<int:course_id>/assignment/submission/<int:submission_id>/download',
         views.download_assignment_submission_content, name='download_submission_content'),

    path('<int:course_id>/list_quiz/', views.list_quizzes, name='list_quizzes'),
    path('<int:course_id>/quiz/', views.add_quiz, name='create_quiz'),
    path('<int:course_id>/quiz/<int:quiz_id>/', views.view_quiz, name='view_quiz'),
    path('<int:course_id>/delete-quiz/<int:quiz_id>/', views.delete_quiz, name='delete_quiz'),
    path('<int:course_id>/quiz/<int:quiz_id>/publish/', views.publish_quiz, name='publish_quiz'),
    path('<int:course_id>/quiz/<int:quiz_id>/unpublish/', views.hide_quiz, name='hide_quiz'),
    path('<int:course_id>/quiz/<int:quiz_id>/attempt', views.attempt_quiz, name='attempt_quiz'),
    path('<int:course_id>/quiz/<int:quiz_id>/view_attempts', views.view_attempts, name='view_attempts'),
    path('quiz/<int:quiz_id>/<int:student_id>/view_attempt', views.view_quiz_attempt, name='view_quiz_attempt'),

    path('<int:course_id>/progress/', views.view_course_progress, name='progress'),
    path('<int:course_id>/grades/', views.list_grades, name='grades'),
    path('<int:course_id>/grades/add/', views.create_extra_grade, name='create_extra_grade'),
    path('<int:course_id>/grades/download_sample_file', views.download_sample_file, name='download_sample_file'),

    path('search/<str:search_keyword>', views.course_search, name='course_search'),

    path('<int:course_id>/list_students/', views.list_students, name='list_students'),
    path('<int:course_id>/view_user_grades/<int:user_id>/', views.view_user_grades, name='view_user_grades'),
    path('<int:course_id>/view_user_progress/<int:user_id>/', views.view_user_progress, name='view_user_progress'),
    
    path('<int:user_id>/view_certificates/', views.view_certificates, name='view_certificates'),
    path('<int:course_id>/generate_certificate/', views.generate_certificate, name='generate_certificate'),
    path('<int:course_id>/certificate/<int:student_id>/', views.generate_certificate, name='generate_certificate_for_student'),

]

scholarstream/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('course.urls', 'course'), namespace='course')),
    path('user/', include('user.urls')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('feedback/', include('feedback.urls')),
    path('chat/', include('chat.urls')),
    path('notifications/', include('notifications.urls')),
]

course/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.db.models import Q
from django.views import View
from django.db import models, transaction
from django.http import FileResponse
from datetime import datetime
from django.utils import timezone
from django.core.files import File
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site

from .forms import *
from .models import *
from cart.cart import Cart
from course.utils import generate_certificate_image
from payment.utils import check_if_user_has_subscription
from notifications.utils import *
from user.models import BlockedUsers

import json
import uuid
import csv
from wsgiref.util import FileWrapper
import io
import os
import shutil
import tempfile
from zipfile import ZipFile
import boto3


@login_required(login_url='login')
def add_course(request):
    user = get_object_or_404(get_user_model(), pk=request.user.pk)
    if user.user_type != 'I':
        return redirect('forbidden')
    if request.method == 'POST':
        form = CourseForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            user.courses.add(Course.objects.last())
            return redirect('course:list')
        else:
            print(form.errors)
            return render(request, 'course/add_course.html', {'form': form})
    else:
        form = CourseForm()

    return render(request, 'course/add_course.html', {'form': form})


def list_course(request):
    if request.user.is_authenticated:
        courses = Course.objects.filter(id__in=request.user.courses.all())
        allcourses = Course.objects.all().exclude(id__in=courses)
        coursesInCart = [item['course'].id for item in Cart(request)]
        allcourses = allcourses.exclude(id__in=coursesInCart)
        return render(request, 'course/list_course.html', {'courses': courses, 'allcourses': allcourses})
    else:
        allcourses = Course.objects.all()
        coursesInCart = [item['course'].id for item in Cart(request)]
        allcourses = allcourses.exclude(id__in=coursesInCart)
        return render(request, 'course/list_course.html', {'allcourses': allcourses})


@login_required(login_url='login')
def course_dashboard(request, pk):
    course = get_object_or_404(Course, pk=pk)
    lessons = Lesson.objects.filter(course=course)
    if request.user.user_type == 'S':
        assignments = Assignment.objects.filter(course=course, is_published=True)
        quizzes = Quiz.objects.filter(course=course, is_published=True)
    else:
        assignments = Assignment.objects.filter(course=course)
        quizzes = Quiz.objects.filter(course=course)
    context = {
        'course': course,
        'assignments': assignments,
        'quizzes': quizzes,
        'lessons': lessons
    }
    return render(request, 'course/dashboard/dashboard.html', context)


@login_required(login_url='login')
def enroll_course(request, pk):
    if request.user.user_type == 'S':
        course = get_object_or_404(Course, pk=pk)
        user = get_object_or_404(get_user_model(), pk=request.user.id)
        user.courses.add(course)
        return redirect('course:list')
    return redirect('course:list')


@login_required(login_url='login')
def dropout(request, pk):
    if request.user.user_type == 'S':
        course = get_object_or_404(Course, pk=pk)
        user = get_object_or_404(get_user_model(), pk=request.user.id)
        user.courses.remove(course)
        return redirect('course:list')
    return redirect('course:list')


@login_required(login_url='login')
def delete_course(request, pk):
    if request.user.user_type == 'I':
        course = get_object_or_404(Course, pk=pk)
        course.delete()
        return redirect('course:list')
    return redirect('forbidden')


class AddLesson(LoginRequiredMixin, View):

    def get(self, request, course_id):
        user = get_object_or_404(get_user_model(), id=request.user.pk)
        if user.user_type != 'I':
            return redirect('forbidden')
        course = get_object_or_404(Course, id=course_id)
        form = LessonForm()
        return render(request, 'course/lesson/add_lesson.html', {'form': form, 'course': course})

    def post(self, request, course_id):
        user = get_object_or_404(get_user_model(), id=request.user.pk)
        if user.user_type != 'I':
            return redirect('forbidden')
        course = get_object_or_404(Course, id=course_id)
        form = LessonForm(request.POST)
        if form.is_valid():
            new_lesson = Lesson(course=course, title=form.cleaned_data['title'])
            new_lesson.save()
            return redirect('course:list_lessons', course_id=course_id)
        else:
            return render(request, 'course/lesson/add_lesson.html', {'form': form, 'course': course})


@login_required(login_url='login')
def list_lessons(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    lessons = course.lessons.prefetch_related('contents__viewed_by').all()
    user = get_user_model().objects.get(username=request.user.username)

    lessons_and_contents = []
    for lesson in lessons:
        contents = lesson.contents.all()
        contents_with_viewed_status = [(content, user in content.viewed_by.all()) for content in contents]
        total_contents = len(contents_with_viewed_status)
        completed_contents = sum(viewed for content, viewed in contents_with_viewed_status)
        progress = (completed_contents / total_contents) * 100 if total_contents else 0
        lessons_and_contents.append((lesson, contents_with_viewed_status, progress))

    context = {
        'lessons': lessons_and_contents,
        'course': course,
        'all_lessons': Lesson.objects.filter(course=course),
        'is_view': False
    }
    return render(request, 'course/lesson/list_lessons.html', context)


@login_required(login_url='login')
def view_lesson(request, course_id, lesson_id):
    course = get_object_or_404(Course, pk=course_id)
    lesson = Lesson.objects.prefetch_related('contents__viewed_by').get(pk=lesson_id)
    user = get_user_model().objects.get(username=request.user.username)

    lessons_and_contents = []
    contents = lesson.contents.all()
    contents_with_viewed_status = [(content, user in content.viewed_by.all()) for content in contents]
    total_contents = len(contents_with_viewed_status)
    completed_contents = sum(viewed for _, viewed in contents_with_viewed_status)
    progress = (completed_contents / total_contents) * 100 if total_contents else 0
    lessons_and_contents.append((lesson, contents_with_viewed_status, progress))

    print(lessons_and_contents)

    context = {
        'lessons': lessons_and_contents,
        'all_lessons': Lesson.objects.filter(course=course),
        'course': course,
        'is_view': True
    }
    return render(request, 'course/lesson/list_lessons.html', context)


class AddContent(LoginRequiredMixin, View):

    def get(self, request, course_id, lesson_id):
        user = get_object_or_404(get_user_model(), id=request.user.pk)
        if user.user_type != 'I':
            return redirect('forbidden')
        form = ContentForm()
        course = get_object_or_404(Course, id=course_id)
        return render(request, 'course/content/add_content.html', {'form': form, 'course': course})

    def post(self, request, course_id, lesson_id):
        user = get_object_or_404(get_user_model(), id=request.user.pk)
        if user.user_type != 'I':
            return redirect('forbidden')
        course = get_object_or_404(Course, id=course_id)
        lesson = get_object_or_404(Lesson, id=lesson_id)
        form = ContentForm(request.POST, request.FILES)
        if form.is_valid():
            new_content = form.save(commit=False)
            new_content.lesson = lesson

            max_order = lesson.contents.aggregate(models.Max('order'))['order__max']
            new_content.order = max_order + 1 if max_order is not None else 0
            new_content.save()
            send_notifications_for_all_students(course, 'course_content', f'New content added to {course.name}', reverse('course:view_content', args=[new_content.id]))
            return redirect('course:view_lesson', course_id, lesson_id)
        else:
            print(form.errors)
            return render(request, 'course/content/add_content.html', {'form': form, 'course': course})


@login_required(login_url='login')
def view_content(request, content_id):
    user = get_object_or_404(get_user_model(), id=request.user.pk)
    content = get_object_or_404(Content, id=content_id)
    course = content.lesson.course
    if request.user.user_type == 'S':
        content.viewed_by.add(user)
        update_progress(user, content.lesson)
    return render(request, 'course/content/view_content.html', {'content': content, 'course': course})


def update_progress(student, lesson):
    progress, created = LessonProgress.objects.get_or_create(
        student=student,
        lesson=lesson,
        defaults={'is_complete': False}
    )

    # Check if all contents for the lesson are viewed by the student.
    contents_in_lesson = Content.objects.filter(lesson=lesson)
    contents_viewed = [content.viewed_by.filter(id=student.id).exists() for content in contents_in_lesson]

    # If all content has been viewed, mark the lesson as complete.
    if all(contents_viewed):
        progress.is_complete = True
        progress.save()


@login_required(login_url='login')
def create_assignment(request, course_id):
    user = get_object_or_404(get_user_model(), id=request.user.pk)
    if user.user_type != 'I':

course/templates/course/grade/create_extra_grade.html
{% extends 'course/dashboard/base_dashboard.html' %}

{% load crispy_forms_tags %}

{% block content %}
<style>

    body {
        background-color: gray;
    }

</style>
<div class="container-fluid col-6 bg-white shadow-md p-5 form-layout">
    <h3>Create Extra Grade</h3>
    <hr><br>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <a href="{% url 'course:download_sample_file' course.id %}" class="btn btn-secondary">Download Sample File</a>
        <br>
        <br>
        <button class="btn btn-primary btn-lg w-100" type="submit">Save</button>
    </form>

</div>
{% endblock content %}

course/templates/course/grade/list_grades_instructor.html
{% extends 'course/dashboard/base_dashboard.html' %}

{% load crispy_forms_tags %}

{% block content %}
<!-- Add the following script and link tags at the top of your template -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-KyZXEAg3QhqLMpG8r+8fhAXT14F0odMsTfZOzoXqtUI=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0/css/bootstrap.min.css" integrity="sha512-UT3d/7Pp/Eq/r2hYr9e5h8Zo+epT/ho9VJsZvP90q+3C2AcJgN5YLMFJ+2VJzC5I8R73m5Db7ZW2b21Dk5Mg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<!-- ... (existing code) ... -->

<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }
    th, td {
        padding: 15px;
        text-align: left;
    }
    th {
        background-color: #f2f2f2;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-4">
            <h3> My Grades </h3>
        </div>
        {% if user.is_authenticated and user.user_type == 'I' %}
        <div class="col">
            <a href="{% url 'course:create_extra_grade' course_id=course.id %}" class="btn btn-primary float-end">Create Extra Grade</a>
        </div>
        {% endif %}
    </div>
    <br>
    
    {% for assignment  in assignments %}
        <h4> {{ assignment.title }} </h4>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Student Name</th>
                    <th>Title</th>
                    <th>Due Date</th>
                    <th>Submission Date</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for progress in assignment.progress.all %}
                        <td>Assignment
                        <td>{{ progress.student.get_full_name }}</td>
                        <td><a href="{% url 'course:view_assignment' course.id assignment.id %}">{{ assignment.title }}</a></td>
                        <td>{{ assignment.due_date }}</td>
                        <td>{{ progress.created_at }}</td>
                        <td>{{ progress.grade }}</td>
                    {% empty %}
                        <td colspan="6" class="text-center">No evaluations done so far</td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
        <br><br>
    {% endfor %}

    {% for quiz, students  in quizzes.items %}
        <h4> {{ quiz.name }} </h4>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Student Name</th>
                    <th>Title</th>
                    <th>Due Date</th>
                    <th>Submission Date</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
                {% for student  in students %}
                    <tr>
                        <td>Quiz</td>
                        <td>{{ student.student }}</td>
                        <td><a href="{% url 'course:view_quiz' course.id quiz.id %}">{{ student.quiz.name }}</a></td>
                        <td>{{ student.quiz.due_date }}</td>
                        <td>{{ student.created_at }}</td>
                        {% if student.total_score and student.total_score != -1 %}
                            <td>{{ student.total_score }}</td>
                        {% else %}
                            <td>
                                <form method='post'>
                                    {% csrf_token %}
                                    {{ quiz_grade_form.total_score | as_crispy_field }}
                                    <input type="hidden" name="student_id" value="{{ student.id }}">
                                    <input type="hidden" name="quiz_id" value="{{ student.quiz.id }}">
                                    <input class="btn btn-primary" type="button" name="view_attempt" value="view_attempt" onclick="openViewAttemptModal({{ quiz.id }}, {{ student.student.id }}, '{{ student.student }}', '{{ student.quiz.name }}', '{{ student.quiz.due_date }}', '{{ student.created_at }}', '{% url 'course:view_quiz_attempt' quiz.id student.student_id %}')">
                                    <button class="btn btn-primary" type="submit" name="quiz_grade_form">
                                        Add Grade
                                    </button>
                                </form>
                            </td>
                        {% endif %}
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6" class="text-center">No quiz evaluations done so far. </td>
                    </tr>
                {% endfor %}

            </tbody>
        </table>
        <br><br>
    {% endfor %}

    {% for otherGrade, students  in otherGrades.items %}
        <h4> {{ otherGrade.name }} </h4>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Student Name</th>
                    <th>Title</th>
                    <th>Due Date</th>
                    <th>Submission Date</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
                {% for student  in students %}
                    <tr>
                        <td>Extra</td>
                        <td>{{ student.student }}</td>
                        <td>{{ student.name }}</td>
                        <td>-</td>
                        <td>{{ student.created_at }}</td>
                        {% if student.grade %}
                            <td>{{ student.grade }}</td>
                        {% else %}
                            <td>Not evaluated</td>
                        {% endif %}
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6" class="text-center">No extra evaluations done so far. </td>
                    </tr>
                {% endfor %}

            </tbody>
        </table>
        <br><br>
    {% endfor %}


</div>
    <!-- ... (existing code) ... -->
<script>
    function openViewAttemptModal(quiz_id, student_id, student, quizName, dueDate, submissionDate, url) {
        // Get the modal element
        const modal = document.getElementById('viewAttemptModal');

        // Update the modal content with the data
        const studentNameElement = modal.querySelector('#studentName');
        const quizNameElement = modal.querySelector('#quizName');
        const dueDateElement = modal.querySelector('#dueDate');
        const submissionDateElement = modal.querySelector('#submissionDate');

        studentNameElement.innerText = student;
        quizNameElement.innerText = quizName;
        dueDateElement.innerText = dueDate;
        submissionDateElement.innerText = submissionDate;

        //let url = '/quiz/' + quiz_id + '/' + student_id + '/view_attempt/'

        fetch(url, {
            'method': 'GET',
        }).then(response => response.json())
        .then(questions => {
            const responseDiv = $('#responseDiv');
            responseDiv.empty();
            for (let question of questions) {
                const questionDiv = $('<div></div>');
                let question_text = question.question_text
                let answer_text = question.answer_text
                questionDiv.append($('<p>').text(question_text))
                questionDiv.append($('<p>').text(answer_text))
                responseDiv.append(questionDiv)
            }
        }).catch((error) => {
            console.log(error)
            const responseDiv = $('#responseDiv');
            responseDiv.empty();
            responseDiv.append($('<p>').text('Failed to get attempt'))
        });

        // Show the modal
        $(modal).modal('show');
    }

    // ... (existing code) ...

    function closeViewAttemptModal() {
        // Get the modal element
        const modal = document.getElementById('viewAttemptModal');
        const responseDiv = $('#responseDiv');
        responseDiv.empty();
        // Hide the modal
        $(modal).modal('hide');
    }


</script>
<!-- ... (existing code) ... -->

<!-- Modal -->
<div class="modal fade" id="viewAttemptModal" tabindex="-1" role="dialog" aria-labelledby="viewAttemptModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="viewAttemptModalLabel">View Attempt Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p><strong>Student Name:</strong> <span id="studentName"></span></p>
                <p><strong>Quiz Name:</strong> <span id="quizName"></span></p>
                <p><strong>Due Date:</strong> <span id="dueDate"></span></p>
                <p><strong>Submission Date:</strong> <span id="submissionDate"></span></p>
                <div id="responseDiv"></div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="closeViewAttemptModal()">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- ... (existing code) ... -->

{% endblock content %}

course/templates/course/grade/list_grades_student.html
{% extends 'course/dashboard/base_dashboard.html' %}

{% load crispy_forms_tags %}

{% block content %}

<style>
    table {
        width: 100%;
        border-collapse: collapse;
    }
    th, td {
        padding: 15px;
        text-align: left;
    }
    th {
        background-color: #f2f2f2;
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-4">
            <h3> My Grades </h3>
        </div>
    </div>
    <br>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Type</th>
            <th>Title</th>
            <th>Due Date</th>
            <th>Evaluation Date</th>
            <th>Grade</th>
        </tr>
    </thead>
    <tbody>
        {% for assignment, progress in assignments.items %}
            <tr>
                <td>Assignment
                <td><a href="{% url 'course:view_assignment' course.id assignment.id %}">{{ assignment.title }}</a></td>
                <td>{{ assignment.due_date }}</td>
                <td>{{ progress.created_at }}</td>
                <td>{{ progress.grade }}</td>
            </tr>
        {% empty %}
            <td class="text-center" colspan="6">No assignment evaluations done so far</td>
        {% endfor %}
        {% for quiz in quizzes %}
            <tr>
                <td>Quiz</td>
                <td><a href="{% url 'course:attempt_quiz' course.id quiz.quiz.id %}">{{ quiz.quiz.name }}</a></td>
                <td>{{ quiz.quiz.due_date }}</td>
                <td>{{ quiz.created_at }}</td>
                {% if quiz.total_score and quiz.total_score != -1 %}
                    <td>{{ quiz.total_score }}</td>
                {% else %}
                    <td>Not evaluated</td>
                {% endif %}
            </tr>
        {% empty %}
            <tr>
                <td colspan="5" class="text-center">No quiz attempts done so far. </td>
            </tr>
        {% endfor %}
        {% for otherGrade in otherGrades %}
            <tr>
                <td>Extra</td>
                <td>{{ otherGrade.name }}</td>
                <td>{{ otherGrade.description }}</td>
                <td>{{ otherGrade.created_at }}</td>
                {% if otherGrade.grade %}
                    <td>{{ otherGrade.grade }}</td>
                {% else %}
                    <td>Not evaluated</td>
                {% endif %}
            </tr>
        {% empty %}
            <tr>
                <td colspan="5" class="text-center">No extra evaluations done so far. </td>
            </tr>
        {% endfor %}

    </tbody>
</table>


</div>
{% endblock content %}