cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_summary, name='summary'),
    path('add/', views.cart_add, name='add'),
    path('delete/', views.cart_delete, name='delete'),

]

course/urls.py
from django.urls import path
from . import views
from .views import AddContent

appname = 'course'

urlpatterns = [
    path('add', views.add_course, name='add'),
    path('', views.list_course, name='list'),
    path('<int:pk>/', views.course_dashboard, name='detail'),
    path('<int:pk>/enroll', views.enroll_course, name='enroll'),
    path('<int:pk>/dropout', views.dropout, name='dropout'),
    path('<int:pk>/delete', views.delete_course, name='delete'),
    
    path('<int:course_id>/add_lesson/', views.AddLesson.as_view(), name='add_lesson'),
    path('<int:course_id>/lessons/', views.list_lessons, name='list_lessons'),
    path('<int:course_id>/lesson/<int:lesson_id>/', views.view_lesson, name='view_lesson'),
    path('<int:course_id>/lesson/<int:lesson_id>/add_content/', AddContent.as_view(), name='add_content'),
    path('content/<int:content_id>/', views.view_content, name='view_content'),
    path('<int:course_id>/download_content', views.download_course_content, name='download_course_content'),
    path('<int:course_id>/<int:lesson_id>/download_content', views.download_course_content,
         name='download_lesson_content'),
    path('<int:course_id>/lesson/<int:lesson_id>/delete/', views.delete_lesson, name='delete_lesson'),
    path('<int:course_id>/content/<int:content_id>/delete/', views.delete_content, name='delete_content'),
    path('<int:course_id>/content/<int:content_id>/publish/', views.publish_content, name='publish_content'),
    path('<int:course_id>/content/<int:content_id>/hide/', views.hide_content, name='hide_content'),

    path('<int:course_id>/create_assignment/', views.create_assignment, name='create_assignment'),
    path('<int:course_id>/assignments/', views.list_assignments, name='list_assignments'),
    path('<int:course_id>/assignment/<int:assignment_id>/', views.view_assignment, name='view_assignment'),
    path('<int:course_id>/assignment/<int:assignment_id>/delete/', views.delete_assignment, name='delete_assignment'),
    path('<int:course_id>/assignment/submission/<int:submission_id>/', views.view_assignment_submission,
         name='view_submission'),
    path('<int:course_id>/assignment/<int:assignment_id>/publish/', views.publish_assignment,
         name='publish_assignment'),
    path('<int:course_id>/assignment/<int:assignment_id>/unpublish/', views.hide_assignment, name='hide_assignment'),
    path('<int:course_id>/assignment/submission/<int:submission_id>/download',
         views.download_assignment_submission_content, name='download_submission_content'),

    path('<int:course_id>/list_quiz/', views.list_quizzes, name='list_quizzes'),
    path('<int:course_id>/quiz/', views.add_quiz, name='create_quiz'),
    path('<int:course_id>/quiz/<int:quiz_id>/', views.view_quiz, name='view_quiz'),
    path('<int:course_id>/delete-quiz/<int:quiz_id>/', views.delete_quiz, name='delete_quiz'),
    path('<int:course_id>/quiz/<int:quiz_id>/publish/', views.publish_quiz, name='publish_quiz'),
    path('<int:course_id>/quiz/<int:quiz_id>/unpublish/', views.hide_quiz, name='hide_quiz'),
    path('<int:course_id>/quiz/<int:quiz_id>/attempt', views.attempt_quiz, name='attempt_quiz'),
    path('<int:course_id>/quiz/<int:quiz_id>/view_attempts', views.view_attempts, name='view_attempts'),
    path('quiz/<int:quiz_id>/<int:student_id>/view_attempt', views.view_quiz_attempt, name='view_quiz_attempt'),

    path('<int:course_id>/progress/', views.view_course_progress, name='progress'),
    path('<int:course_id>/grades/', views.list_grades, name='grades'),
    path('<int:course_id>/grades/add/', views.create_extra_grade, name='create_extra_grade'),
    path('<int:course_id>/grades/download_sample_file', views.download_sample_file, name='download_sample_file'),

    path('search/<str:search_keyword>', views.course_search, name='course_search'),

    path('<int:course_id>/list_students/', views.list_students, name='list_students'),
    path('<int:course_id>/view_user_grades/<int:user_id>/', views.view_user_grades, name='view_user_grades'),
    path('<int:course_id>/view_user_progress/<int:user_id>/', views.view_user_progress, name='view_user_progress'),
    
    path('<int:user_id>/view_certificates/', views.view_certificates, name='view_certificates'),
    path('<int:course_id>/generate_certificate/', views.generate_certificate, name='generate_certificate'),
    path('<int:course_id>/certificate/<int:student_id>/', views.generate_certificate, name='generate_certificate_for_student'),

]

scholarstream/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('course.urls', 'course'), namespace='course')),
    path('user/', include('user.urls')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('feedback/', include('feedback.urls')),
    path('chat/', include('chat.urls')),
    path('notifications/', include('notifications.urls')),
]

course/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.db.models import Q
from django.views import View
from django.db import models, transaction
from django.http import FileResponse
from datetime import datetime
from django.utils import timezone
from django.core.files import File
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site

from .forms import *
from .models import *
from cart.cart import Cart
from course.utils import generate_certificate_image
from payment.utils import check_if_user_has_subscription
from notifications.utils import *
from user.models import BlockedUsers

import json
import uuid
import csv
from wsgiref.util import FileWrapper
import io
import os
import shutil
import tempfile
from zipfile import ZipFile
import boto3


@login_required(login_url='login')
def add_course(request):
    user = get_object_or_404(get_user_model(), pk=request.user.pk)
    if user.user_type != 'I':
        return redirect('forbidden')
    if request.method == 'POST':
        form = CourseForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            user.courses.add(Course.objects.last())
            return redirect('course:list')
        else:
            print(form.errors)
            return render(request, 'course/add_course.html', {'form': form})
    else:
        form = CourseForm()

    return render(request, 'course/add_course.html', {'form': form})


def list_course(request):
    if request.user.is_authenticated:
        courses = Course.objects.filter(id__in=request.user.courses.all())
        allcourses = Course.objects.all().exclude(id__in=courses)
        coursesInCart = [item['course'].id for item in Cart(request)]
        allcourses = allcourses.exclude(id__in=coursesInCart)
        return render(request, 'course/list_course.html', {'courses': courses, 'allcourses': allcourses})
    else:
        allcourses = Course.objects.all()
        coursesInCart = [item['course'].id for item in Cart(request)]
        allcourses = allcourses.exclude(id__in=coursesInCart)
        return render(request, 'course/list_course.html', {'allcourses': allcourses})


@login_required(login_url='login')
def course_dashboard(request, pk):
    course = get_object_or_404(Course, pk=pk)
    lessons = Lesson.objects.filter(course=course)
    if request.user.user_type == 'S':
        assignments = Assignment.objects.filter(course=course, is_published=True)
        quizzes = Quiz.objects.filter(course=course, is_published=True)
    else:
        assignments = Assignment.objects.filter(course=course)
        quizzes = Quiz.objects.filter(course=course)
    context = {
        'course': course,
        'assignments': assignments,
        'quizzes': quizzes,
        'lessons': lessons
    }
    return render(request, 'course/dashboard/dashboard.html', context)


@login_required(login_url='login')
def enroll_course(request, pk):
    if request.user.user_type == 'S':
        course = get_object_or_404(Course, pk=pk)
        user = get_object_or_404(get_user_model(), pk=request.user.id)
        user.courses.add(course)
        return redirect('course:list')
    return redirect('course:list')


@login_required(login_url='login')
def dropout(request, pk):
    if request.user.user_type == 'S':
        course = get_object_or_404(Course, pk=pk)
        user = get_object_or_404(get_user_model(), pk=request.user.id)
        user.courses.remove(course)
        return redirect('course:list')
    return redirect('course:list')


@login_required(login_url='login')
def delete_course(request, pk):
    if request.user.user_type == 'I':
        course = get_object_or_404(Course, pk=pk)
        course.delete()
        return redirect('course:list')
    return redirect('forbidden')


class AddLesson(LoginRequiredMixin, View):

    def get(self, request, course_id):
        user = get_object_or_404(get_user_model(), id=request.user.pk)
        if user.user_type != 'I':
            return redirect('forbidden')
        course = get_object_or_404(Course, id=course_id)
        form = LessonForm()
        return render(request, 'course/lesson/add_lesson.html', {'form': form, 'course': course})

    def post(self, request, course_id):
        user = get_object_or_404(get_user_model(), id=request.user.pk)
        if user.user_type != 'I':
            return redirect('forbidden')
        course = get_object_or_404(Course, id=course_id)
        form = LessonForm(request.POST)
        if form.is_valid():
            new_lesson = Lesson(course=course, title=form.cleaned_data['title'])
            new_lesson.save()
            return redirect('course:list_lessons', course_id=course_id)
        else:
            return render(request, 'course/lesson/add_lesson.html', {'form': form, 'course': course})


@login_required(login_url='login')
def list_lessons(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    lessons = course.lessons.prefetch_related('contents__viewed_by').all()
    user = get_user_model().objects.get(username=request.user.username)

    lessons_and_contents = []
    for lesson in lessons:
        contents = lesson.contents.all()
        contents_with_viewed_status = [(content, user in content.viewed_by.all()) for content in contents]
        total_contents = len(contents_with_viewed_status)
        completed_contents = sum(viewed for content, viewed in contents_with_viewed_status)
        progress = (completed_contents / total_contents) * 100 if total_contents else 0
        lessons_and_contents.append((lesson, contents_with_viewed_status, progress))

    context = {
        'lessons': lessons_and_contents,
        'course': course,
        'all_lessons': Lesson.objects.filter(course=course),
        'is_view': False
    }
    return render(request, 'course/lesson/list_lessons.html', context)


@login_required(login_url='login')
def view_lesson(request, course_id, lesson_id):
    course = get_object_or_404(Course, pk=course_id)
    lesson = Lesson.objects.prefetch_related('contents__viewed_by').get(pk=lesson_id)
    user = get_user_model().objects.get(username=request.user.username)

    lessons_and_contents = []
    contents = lesson.contents.all()
    contents_with_viewed_status = [(content, user in content.viewed_by.all()) for content in contents]
    total_contents = len(contents_with_viewed_status)
    completed_contents = sum(viewed for _, viewed in contents_with_viewed_status)
    progress = (completed_contents / total_contents) * 100 if total_contents else 0
    lessons_and_contents.append((lesson, contents_with_viewed_status, progress))

    print(lessons_and_contents)

    context = {
        'lessons': lessons_and_contents,
        'all_lessons': Lesson.objects.filter(course=course),
        'course': course,
        'is_view': True
    }
    return render(request, 'course/lesson/list_lessons.html', context)


class AddContent(LoginRequiredMixin, View):

    def get(self, request, course_id, lesson_id):
        user = get_object_or_404(get_user_model(), id=request.user.pk)
        if user.user_type != 'I':
            return redirect('forbidden')
        form = ContentForm()
        course = get_object_or_404(Course, id=course_id)
        return render(request, 'course/content/add_content.html', {'form': form, 'course': course})

    def post(self, request, course_id, lesson_id):
        user = get_object_or_404(get_user_model(), id=request.user.pk)
        if user.user_type != 'I':
            return redirect('forbidden')
        course = get_object_or_404(Course, id=course_id)
        lesson = get_object_or_404(Lesson, id=lesson_id)
        form = ContentForm(request.POST, request.FILES)
        if form.is_valid():
            new_content = form.save(commit=False)
            new_content.lesson = lesson

            max_order = lesson.contents.aggregate(models.Max('order'))['order__max']
            new_content.order = max_order + 1 if max_order is not None else 0
            new_content.save()
            send_notifications_for_all_students(course, 'course_content', f'New content added to {course.name}', reverse('course:view_content', args=[new_content.id]))
            return redirect('course:view_lesson', course_id, lesson_id)
        else:
            print(form.errors)
            return render(request, 'course/content/add_content.html', {'form': form, 'course': course})


@login_required(login_url='login')
def view_content(request, content_id):
    user = get_object_or_404(get_user_model(), id=request.user.pk)
    content = get_object_or_404(Content, id=content_id)
    course = content.lesson.course
    if request.user.user_type == 'S':
        content.viewed_by.add(user)
        update_progress(user, content.lesson)
    return render(request, 'course/content/view_content.html', {'content': content, 'course': course})


def update_progress(student, lesson):
    progress, created = LessonProgress.objects.get_or_create(
        student=student,
        lesson=lesson,
        defaults={'is_complete': False}
    )

    # Check if all contents for the lesson are viewed by the student.
    contents_in_lesson = Content.objects.filter(lesson=lesson)
    contents_viewed = [content.viewed_by.filter(id=student.id).exists() for content in contents_in_lesson]

    # If all content has been viewed, mark the lesson as complete.
    if all(contents_viewed):
        progress.is_complete = True
        progress.save()


@login_required(login_url='login')
def create_assignment(request, course_id):
    user = get_object_or_404(get_user_model(), id=request.user.pk)
    if user.user_type != 'I':

course/templates/course/lesson/add_lesson.html
{% extends 'course/dashboard/base_dashboard.html' %}

{% load crispy_forms_tags %}

{% block content %}
<style>

    body {
        background-color: gray;
    }

</style>
<div class="container-fluid col-6 bg-white shadow-md p-5 form-layout">
    <h3>Add Folder/Lesson</h3>
    <hr><br>

    <form method="post">
        {% csrf_token %}
        {{ form | crispy}}
        
        <button class="btn btn-primary btn-lg w-100" type="submit">Add Folder/Lesson</button>
    </form>

</div>
{% endblock content %}

course/templates/course/lesson/list_lessons.html
{% extends 'course/dashboard/base_dashboard.html' %}

{% load crispy_forms_tags %}

{% block content %}

    <style>
        a {
            text-decoration: none;
            color: black;
        }

        body {
            background-color: white;
        }
    </style>

    <div class="container-fluid">
        <div class="row">
            <!-- Left Navigation Pane -->
            <div class="col-md-2 mr-3 ms-3 p-3 text-center" style="background-color: gray; height: 100vh; overflow-y: auto; border: 2px solid black;">
                <h4> Table of Contents </h4>
                <ul class="nav nav-pills flex-column">
                    {% for lesson  in all_lessons %}
                        <li class="nav-item">
                            <a {% if is_view and lesson.id == lessons.0.0.id %} class="nav-link active"
                                aria-current="page" {% else %} class="nav-link" {% endif %}
                                href="{% url 'course:view_lesson' course_id=course.id lesson_id=lesson.id %}"
                                class="nav-link"> {{ lesson.title }} </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>

            <div class="col-md-9">

                <div class="container-fluid p-5 bg-white">
                    <div class="row">
                        <div class="col-md-6">
                            {% if is_view %}
                                <h3>Lesson Content</h3>
                            {% else %}
                                <h3>Course Content</h3>
                            {% endif %}
                        </div>
                        <div class="col-md-6">
                            {% if user.is_authenticated and user.user_type == 'I' %}
                                <a href="{% url 'course:add_lesson' course_id=course.id %}"
                                    class="btn btn-primary float-end">Add Folder/Lecture</a>
                            {% endif %}
                            {% if not is_view %}
                                <a href="{% url 'course:download_course_content' course.id %}"
                                    class="btn btn-primary float-end me-2"><i class="fa fa-download"></i> Download</a>
                            {% endif %}
                        </div>
                    </div>
                    <br>
                    <div class="accordion" id="accordionLesson">
                        {% for lesson, contents, progress in lessons %}

                            <div class="accordion-item">
                                <h2 class="accordion-header" id="{{ lesson.id }}">
                                    <div class="d-flex justify-content-between">
                                        <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                                data-bs-target="#collapse{{ lesson.id }}" aria-expanded="true"
                                                aria-controls="collapse{{ lesson.id }}">
                                            {{ lesson.title }}
                                        </button>
                                        <a href="{% url 'course:download_lesson_content' course.id lesson.id %}"
                                            class="btn btn-primary m-2"><i class="fa fa-download"></i></a>
                                        
                                        {% if user.user_type == 'I' %}
                                            <a href="{% url 'course:delete_lesson' course.id lesson.id %}"
                                                class="btn btn-danger m-2"><i class="fa fa-trash"></i></a>
                                        {% endif %}
                                    </div>
                                </h2>
                                {% if user.user_type == 'S' %}
                                    <div class="progress">
                                        <div class="progress-bar" role="progressbar" style="width: {{ progress }}%;"
                                            aria-valuenow="{{ progress }}" aria-valuemin="0"
                                            aria-valuemax="100">{{ progress }}%
                                        </div>
                                    </div>
                                {% endif %}
                                {% if user.is_authenticated and user.user_type == 'I' %}
                                    <div class="row">
                                        <a href="{% url 'course:add_content' course_id=course.id lesson_id=lesson.id %}"
                                           class="offset-md-9 col-md-2 mt-2 mr-5 btn btn-primary">Add Content</a>
                                    </div>
                                {% endif %}
                                <br>
                                <div id="collapse{{ lesson.id }}" class="accordion-collapse collapse show"
                                     aria-labelledby="{{ lesson.id }}" data-bs-parent="#accordionLesson">
                                    <div class="accordion-body">
                                        {% if contents|length == 0 %}
                                            <p>No content available</p>
                                        {% endif %}
                                        {% for content, viewed in contents %}
                                            {% if user.user_type == 'I' %}
                                                    <div class="card bg-secondary text-white text-center mb-4">
                                                        <div class="card-body">
                                                            <div class="row">
                                                                <div class="col-md-3">
                                                                    <a class="content-link" href="{% url 'course:view_content' content_id=content.id %}">
                                                                        <h5 class="">{{ content.title }}</h5></a>
                                                                    {% if content.is_published %}
                                                                        <span class="badge bg-light text-dark">Published</span>
                                                                    {% else %}
                                                                        <span class="badge bg-light text-dark">Unpublished</span>
                                                                    {% endif %}
                                                                </div>
                                                                <div class="col-md-9">
                                                                    <a href="{% url 'course:delete_content' course.id content.id %}"
                                                                    class="btn btn-danger m-2 float-end"><i class="fa fa-trash"></i></a>
                                                                    {% if content.is_published %}
                                                                        <a href="{% url 'course:hide_content' course.id content.id %}"
                                                                            class="btn m-2 float-end"><i class="fa fa-eye-slash"></i></a>
                                                                    {% else %}
                                                                        <a href="{% url 'course:publish_content' course.id content.id %}"
                                                                            class="btn m-2 float-end"><i class="fa fa-eye"></i></a>
                                                                    {% endif %}
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                            
                                            {% else %}
                                                {% if content.is_published %}
                                                    <a class="content-link {% if viewed %}viewed{% endif %}"
                                                    href="{% url 'course:view_content' content_id=content.id %}">
                                                        <div class="card {% if viewed %}bg-success{% else %}bg-secondary{% endif %} text-white text-center mb-4">
                                                            <div class="card-body">
                                                                <h5 class="text-center card-title">{{ content.title }}</h5>
                                                                {% if viewed %}
                                                                    <span class="badge bg-light text-dark">Completed</span>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                    </a>
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% empty %}
                            <p>No content available</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
{% endblock %}